version: '3.8'

services:
  embedding-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - MODEL_PATH=/app/model
      - MODEL_NAME=paraphrase-multilingual-mpnet-base-v2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G 