version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant_legal_chatbot
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API & Web UI
      - "6334:6334"  # gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage  # Lưu trữ dữ liệu vector
    environment:
      QDRANT__SERVICE__API_KEY: "my_super_secret_key"  # API key để bảo mật
    networks:
      - qdrant_network

networks:
  qdrant_network:
    name: qdrant_network
    driver: bridge 