version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: nttu-chatbot-frontend
    ports:
      - "30001:30001"
    restart: unless-stopped
    networks:
      - nttu-network
    volumes:
      - ./front-end/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  nttu-network:
    driver: bridge 